# numpy

NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

https://www.w3schools.com/python/numpy/numpy_intro.asp#:~:text=NumPy%20is%20a%20Python%20library,you%20can%20use%20it%20freely.

In [1]:
import numpy as np

## lets to some basic stuff

In [2]:
array = np.array(5)
array

array(5)

In [3]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
array.shape

(20,)

In [5]:
reshape_array = array.reshape(2, 5, 2)
reshape_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [6]:
print(reshape_array.shape)
print(reshape_array.ndim)
print(reshape_array.size)
print(reshape_array.dtype)

(2, 5, 2)
3
20
int32


In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.zeros((3, 4)) == np.zeros([3, 4])

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## some operations

In [11]:
array_a = np.array([20, 30, 40, 50])
array_b = np.arange(4)

print(array_a)
print(array_b)

[20 30 40 50]
[0 1 2 3]


In [12]:
array_a - array_b

array([20, 29, 38, 47])

In [13]:
array_a + array_b

array([20, 31, 42, 53])

In [14]:
array_c = array_a * array_b
array_c

array([  0,  30,  80, 150])

In [15]:
array_c > 50

array([False, False,  True,  True])

In [16]:
np.sinc(array_c)

array([ 1.00000000e+00, -1.14372644e-16, -3.89817183e-17, -5.40599035e-17])